add http/grpc header support for py/js functions
OpenFogStack/tinyFaaS pull request #40
Opened 2024-08-08 10:53 UTC by ChaosRez

- update function handler for python + JS
- pass grpc headers (metadata)
- pass http headers (http.go)
- update rproxy to pass the headers to function handlers
- test it to log print the headers
- update python and js examples
- update readme to mention this change

2024-08-08 12:00 UTC, pfandzelter requested changes

2024-08-08 12:00 UTC, pfandzelter commented on pkg/rproxy/rproxy.go
> +	req, err := http.NewRequest("POST", fmt.Sprintf("http://%s:8000/fn", h), bytes.NewBuffer(payload))
We now build the request twice, once for async and one for sync. Maybe build it once and put only `Do(req)` twice?

2024-08-08 12:00 UTC, pfandzelter commented on pkg/grpc/grpc.go
> +		return nil, fmt.Errorf("failed to extract metadata from context")
If extracting metadata fails (`ok == false`), why not set an empty header list? Do we need to fail in this case, it's not an error

2024-08-08 12:00 UTC, pfandzelter commented on test/fns/echo/fn.py
> +        print ("headers: " + str(headers))
Instead of adding header printing to the existing `echo` and `sieve` functions, it would be good to add dedicated functions and tests for headers to make sure they behave as expected. Maybe a `header` function in Python/Node that returns incoming headers, plus new test cases in `tests/`. That will also be better to illustrate how headers work

2024-08-08 12:05 UTC, ChaosRez commented on pkg/rproxy/rproxy.go
> +	req, err := http.NewRequest("POST", fmt.Sprintf("http://%s:8000/fn", h), bytes.NewBuffer(payload))
text-wise yes, but one only run. but okay

2024-08-19 12:25 UTC, pfandzelter approved these changes

2024-08-19 12:35 UTC, merged